FROM alpine:3.20

RUN apk add --no-cache nodejs npm

RUN addgroup -g 1000 vite \
 && adduser -u 1000 -S vite -G vite

WORKDIR /var/www/chivalrous.com

COPY ./php-fpm/project/package*.json ./

RUN npm ci

RUN chown -R vite:vite /var/www/chivalrous.com

EXPOSE 5173

USER vite

CMD ["npm", "run", "dev"]