FROM nginxinc/nginx-unprivileged:1.24-alpine

ARG UID
ARG GID

USER root

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/dev.chivalrous.com/ /etc/nginx/sites-available/dev.chivalrous.com
COPY ./nginx/chivalrous.com/ /etc/nginx/sites-available/chivalrous.com
COPY ./php-fpm/project/resources /var/www/chivalrous.com/resources/

RUN mkdir -p /var/www/chivalrous.com/public \
    && mkdir -p /var/www/dev.chivalrous.com/public \
    && mkdir -p /var/log/nginx \ 
    && mkdir -p /var/log/nginx/chivalrous.com \
    && mkdir -p /var/log/nginx/dev.chivalrous.com \
    && mkdir -p /etc/nginx/sites-enabled/ \
    && chown -R nginx:nginx /var/www /var/log/nginx /etc/nginx/sites-available /etc/nginx/sites-enabled

RUN ln -s /etc/nginx/sites-available/dev.chivalrous.com /etc/nginx/sites-enabled/ \
    && ln -s /etc/nginx/sites-available/chivalrous.com /etc/nginx/sites-enabled/
